version: "3.3"

services:

  movierama:
    image: movierama
    build:
      context: ./../../../
      dockerfile: ./infra/deploy/build/Dockerfile
    container_name: movierama
    restart: on-failure
    ports:
      - "1323:1323"
    env_file:
      - ./../../../.env.test
    depends_on:
      - movierama_db

  movierama_ci:
    image: movierama_ci
    build:
      context: ./../../../
      dockerfile: ./infra/deploy/ci/Dockerfile
    container_name: movierama_ci
    env_file:
      - ./../../../.env.test
    environment:
      MYSQL_READ: "movierama_ci_db"
      MYSQL_WRITE: "movierama_ci_db"
    depends_on:
      - movierama_ci_db

  movierama_ci_db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "movierama"

  movierama_db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "movierama"
    ports:
      - "3306:3306"
